server:
  port: 8001

apollo:
  cacheDir: /Users/zhangbaohao/temp/apollo/reviews
  bootstrap:
    enabled: true

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: reviews
      ip: 127.0.0.1
      port: 8888
      logpath: /Users/zhangbaohao/temp/applogs/xxl-job/jobhandler
      logretentiondays: -1
    accessToken: 