server:
  port: 9080

apollo:
  cacheDir: /tmp/reviews/apollo
  bootstrap:
    enabled: true
    namespaces: application,public.egret

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: reviews
      ip: 
      port: 9999
      logpath: /tmp/reviews/xxl-job
      logretentiondays: -1
    accessToken: 