server:
  port: 5001

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
  security:
    user:
      name: _config
      password: _linux